# Generated by Django 5.1.1 on 2024-09-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_expense_date_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expenses',
        ),
    ]
